//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicePago {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePago.WebServiceMantenedorPagoSoap")]
    public interface WebServiceMantenedorPagoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPagoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarPagoService(CapaGUI.ServicePago.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPagoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarPagoServiceAsync(CapaGUI.ServicePago.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminiarPagoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminiarPagoService(int id_pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminiarPagoService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminiarPagoServiceAsync(int id_pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPagoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarPagoService(CapaGUI.ServicePago.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPagoService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarPagoServiceAsync(CapaGUI.ServicePago.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPagoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicePago.Pago buscarPagoService(System.DateTime fecha_pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPagoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServicePago.Pago> buscarPagoServiceAsync(System.DateTime fecha_pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPagoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornaPagoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPagoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornaPagoServiceAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_pagoField;
        
        private System.DateTime fecha_pagoField;
        
        private int total_pagoField;
        
        private int id_tipopagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_pago {
            get {
                return this.id_pagoField;
            }
            set {
                this.id_pagoField = value;
                this.RaisePropertyChanged("Id_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha_pago {
            get {
                return this.fecha_pagoField;
            }
            set {
                this.fecha_pagoField = value;
                this.RaisePropertyChanged("Fecha_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Total_pago {
            get {
                return this.total_pagoField;
            }
            set {
                this.total_pagoField = value;
                this.RaisePropertyChanged("Total_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Id_tipopago {
            get {
                return this.id_tipopagoField;
            }
            set {
                this.id_tipopagoField = value;
                this.RaisePropertyChanged("Id_tipopago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorPagoSoapChannel : CapaGUI.ServicePago.WebServiceMantenedorPagoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorPagoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServicePago.WebServiceMantenedorPagoSoap>, CapaGUI.ServicePago.WebServiceMantenedorPagoSoap {
        
        public WebServiceMantenedorPagoSoapClient() {
        }
        
        public WebServiceMantenedorPagoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorPagoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorPagoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorPagoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarPagoService(CapaGUI.ServicePago.Pago pago) {
            base.Channel.insertarPagoService(pago);
        }
        
        public System.Threading.Tasks.Task insertarPagoServiceAsync(CapaGUI.ServicePago.Pago pago) {
            return base.Channel.insertarPagoServiceAsync(pago);
        }
        
        public void eliminiarPagoService(int id_pago) {
            base.Channel.eliminiarPagoService(id_pago);
        }
        
        public System.Threading.Tasks.Task eliminiarPagoServiceAsync(int id_pago) {
            return base.Channel.eliminiarPagoServiceAsync(id_pago);
        }
        
        public void actualizarPagoService(CapaGUI.ServicePago.Pago pago) {
            base.Channel.actualizarPagoService(pago);
        }
        
        public System.Threading.Tasks.Task actualizarPagoServiceAsync(CapaGUI.ServicePago.Pago pago) {
            return base.Channel.actualizarPagoServiceAsync(pago);
        }
        
        public CapaGUI.ServicePago.Pago buscarPagoService(System.DateTime fecha_pago) {
            return base.Channel.buscarPagoService(fecha_pago);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicePago.Pago> buscarPagoServiceAsync(System.DateTime fecha_pago) {
            return base.Channel.buscarPagoServiceAsync(fecha_pago);
        }
        
        public System.Data.DataSet retornaPagoService() {
            return base.Channel.retornaPagoService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornaPagoServiceAsync() {
            return base.Channel.retornaPagoServiceAsync();
        }
    }
}
