//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceConductor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceConductor.WebServiceMantenedorConductorSoap")]
    public interface WebServiceMantenedorConductorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarConductorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IPersistentBase))]
        CapaGUI.ServiceConductor.ResponseTransaction insertarConductorService(CapaGUI.ServiceConductor.Conductor conductor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarConductorService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceConductor.ResponseTransaction> insertarConductorServiceAsync(CapaGUI.ServiceConductor.Conductor conductor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminiarConductorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IPersistentBase))]
        CapaGUI.ServiceConductor.ResponseTransaction eliminiarConductorService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminiarConductorService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceConductor.ResponseTransaction> eliminiarConductorServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarConductorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IPersistentBase))]
        void actualizarConductorService(CapaGUI.ServiceConductor.Conductor conductor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarConductorService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarConductorServiceAsync(CapaGUI.ServiceConductor.Conductor conductor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarConductorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IPersistentBase))]
        CapaGUI.ServiceConductor.Conductor buscarConductorService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarConductorService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceConductor.Conductor> buscarConductorServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaConductorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IPersistentBase))]
        System.Data.DataSet retornaConductorService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaConductorService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornaConductorServiceAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Conductor : IPersistentBase {
        
        private string rutField;
        
        private string nombresField;
        
        private string apellido_paternoField;
        
        private string apellido_maternoField;
        
        private string sexoField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("Nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellido_paterno {
            get {
                return this.apellido_paternoField;
            }
            set {
                this.apellido_paternoField = value;
                this.RaisePropertyChanged("Apellido_paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apellido_materno {
            get {
                return this.apellido_maternoField;
            }
            set {
                this.apellido_maternoField = value;
                this.RaisePropertyChanged("Apellido_materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Conductor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class IPersistentBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool _isDeletedField;
        
        private bool _isNewField;
        
        private bool _isModifiedField;
        
        private bool _isBlockedField;
        
        private int _idField;
        
        private object _timeStampField;
        
        private bool _isActiveField;
        
        private System.DateTime _creationDateField;
        
        private bool isDeletedField;
        
        private bool isNewField;
        
        private bool isBlockedField;
        
        private int idField;
        
        private object timeStampField;
        
        private System.DateTime creationDateField;
        
        private object tagField;
        
        private bool isActiveField;
        
        private bool isModifiedField;
        
        public IPersistentBase() {
            this.isBlockedField = false;
            this.isModifiedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool _isDeleted {
            get {
                return this._isDeletedField;
            }
            set {
                this._isDeletedField = value;
                this.RaisePropertyChanged("_isDeleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool _isNew {
            get {
                return this._isNewField;
            }
            set {
                this._isNewField = value;
                this.RaisePropertyChanged("_isNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool _isModified {
            get {
                return this._isModifiedField;
            }
            set {
                this._isModifiedField = value;
                this.RaisePropertyChanged("_isModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool _isBlocked {
            get {
                return this._isBlockedField;
            }
            set {
                this._isBlockedField = value;
                this.RaisePropertyChanged("_isBlocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                this._idField = value;
                this.RaisePropertyChanged("_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object _timeStamp {
            get {
                return this._timeStampField;
            }
            set {
                this._timeStampField = value;
                this.RaisePropertyChanged("_timeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool _isActive {
            get {
                return this._isActiveField;
            }
            set {
                this._isActiveField = value;
                this.RaisePropertyChanged("_isActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime _creationDate {
            get {
                return this._creationDateField;
            }
            set {
                this._creationDateField = value;
                this.RaisePropertyChanged("_creationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
                this.RaisePropertyChanged("IsDeleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
                this.RaisePropertyChanged("IsNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsBlocked {
            get {
                return this.isBlockedField;
            }
            set {
                this.isBlockedField = value;
                this.RaisePropertyChanged("IsBlocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public object TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public object Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsModified {
            get {
                return this.isModifiedField;
            }
            set {
                this.isModifiedField = value;
                this.RaisePropertyChanged("IsModified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorConductorSoapChannel : CapaGUI.ServiceConductor.WebServiceMantenedorConductorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorConductorSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceConductor.WebServiceMantenedorConductorSoap>, CapaGUI.ServiceConductor.WebServiceMantenedorConductorSoap {
        
        public WebServiceMantenedorConductorSoapClient() {
        }
        
        public WebServiceMantenedorConductorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorConductorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorConductorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorConductorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaGUI.ServiceConductor.ResponseTransaction insertarConductorService(CapaGUI.ServiceConductor.Conductor conductor) {
            return base.Channel.insertarConductorService(conductor);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceConductor.ResponseTransaction> insertarConductorServiceAsync(CapaGUI.ServiceConductor.Conductor conductor) {
            return base.Channel.insertarConductorServiceAsync(conductor);
        }
        
        public CapaGUI.ServiceConductor.ResponseTransaction eliminiarConductorService(string rut) {
            return base.Channel.eliminiarConductorService(rut);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceConductor.ResponseTransaction> eliminiarConductorServiceAsync(string rut) {
            return base.Channel.eliminiarConductorServiceAsync(rut);
        }
        
        public void actualizarConductorService(CapaGUI.ServiceConductor.Conductor conductor) {
            base.Channel.actualizarConductorService(conductor);
        }
        
        public System.Threading.Tasks.Task actualizarConductorServiceAsync(CapaGUI.ServiceConductor.Conductor conductor) {
            return base.Channel.actualizarConductorServiceAsync(conductor);
        }
        
        public CapaGUI.ServiceConductor.Conductor buscarConductorService(string rut) {
            return base.Channel.buscarConductorService(rut);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceConductor.Conductor> buscarConductorServiceAsync(string rut) {
            return base.Channel.buscarConductorServiceAsync(rut);
        }
        
        public System.Data.DataSet retornaConductorService() {
            return base.Channel.retornaConductorService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornaConductorServiceAsync() {
            return base.Channel.retornaConductorServiceAsync();
        }
    }
}
