//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceViaje {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceViaje.WebServiceMantenedorViajeSoap")]
    public interface WebServiceMantenedorViajeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarViajeService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarViajeService(CapaGUI.ServiceViaje.Viaje viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarViajeService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarViajeServiceAsync(CapaGUI.ServiceViaje.Viaje viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminiarViajeService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminiarViajeService(int id_viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminiarViajeService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminiarViajeServiceAsync(int id_viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarViajeService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarViajeService(CapaGUI.ServiceViaje.Viaje viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarViajeService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarViajeServiceAsync(CapaGUI.ServiceViaje.Viaje viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarViajeService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceViaje.Viaje buscarViajeService(int id_viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarViajeService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceViaje.Viaje> buscarViajeServiceAsync(int id_viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaViajerService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornaViajerService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaViajerService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornaViajerServiceAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Viaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_viajeField;
        
        private System.DateTime fecha_viajeField;
        
        private int distanciaField;
        
        private int tarifa_viajeField;
        
        private string nombre_servicioField;
        
        private string rutField;
        
        private string lugar_destinoField;
        
        private string lugar_origenField;
        
        private int id_pagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_viaje {
            get {
                return this.id_viajeField;
            }
            set {
                this.id_viajeField = value;
                this.RaisePropertyChanged("Id_viaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha_viaje {
            get {
                return this.fecha_viajeField;
            }
            set {
                this.fecha_viajeField = value;
                this.RaisePropertyChanged("Fecha_viaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Distancia {
            get {
                return this.distanciaField;
            }
            set {
                this.distanciaField = value;
                this.RaisePropertyChanged("Distancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Tarifa_viaje {
            get {
                return this.tarifa_viajeField;
            }
            set {
                this.tarifa_viajeField = value;
                this.RaisePropertyChanged("Tarifa_viaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nombre_servicio {
            get {
                return this.nombre_servicioField;
            }
            set {
                this.nombre_servicioField = value;
                this.RaisePropertyChanged("Nombre_servicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Lugar_destino {
            get {
                return this.lugar_destinoField;
            }
            set {
                this.lugar_destinoField = value;
                this.RaisePropertyChanged("Lugar_destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Lugar_origen {
            get {
                return this.lugar_origenField;
            }
            set {
                this.lugar_origenField = value;
                this.RaisePropertyChanged("Lugar_origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Id_pago {
            get {
                return this.id_pagoField;
            }
            set {
                this.id_pagoField = value;
                this.RaisePropertyChanged("Id_pago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorViajeSoapChannel : CapaGUI.ServiceViaje.WebServiceMantenedorViajeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorViajeSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceViaje.WebServiceMantenedorViajeSoap>, CapaGUI.ServiceViaje.WebServiceMantenedorViajeSoap {
        
        public WebServiceMantenedorViajeSoapClient() {
        }
        
        public WebServiceMantenedorViajeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorViajeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorViajeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorViajeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarViajeService(CapaGUI.ServiceViaje.Viaje viaje) {
            base.Channel.insertarViajeService(viaje);
        }
        
        public System.Threading.Tasks.Task insertarViajeServiceAsync(CapaGUI.ServiceViaje.Viaje viaje) {
            return base.Channel.insertarViajeServiceAsync(viaje);
        }
        
        public void eliminiarViajeService(int id_viaje) {
            base.Channel.eliminiarViajeService(id_viaje);
        }
        
        public System.Threading.Tasks.Task eliminiarViajeServiceAsync(int id_viaje) {
            return base.Channel.eliminiarViajeServiceAsync(id_viaje);
        }
        
        public void actualizarViajeService(CapaGUI.ServiceViaje.Viaje viaje) {
            base.Channel.actualizarViajeService(viaje);
        }
        
        public System.Threading.Tasks.Task actualizarViajeServiceAsync(CapaGUI.ServiceViaje.Viaje viaje) {
            return base.Channel.actualizarViajeServiceAsync(viaje);
        }
        
        public CapaGUI.ServiceViaje.Viaje buscarViajeService(int id_viaje) {
            return base.Channel.buscarViajeService(id_viaje);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceViaje.Viaje> buscarViajeServiceAsync(int id_viaje) {
            return base.Channel.buscarViajeServiceAsync(id_viaje);
        }
        
        public System.Data.DataSet retornaViajerService() {
            return base.Channel.retornaViajerService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornaViajerServiceAsync() {
            return base.Channel.retornaViajerServiceAsync();
        }
    }
}
